/*
 * lnbits
 *
 * API for LNbits, the free and open source bitcoin wallet and accounts system with plugins.
 *
 * The version of the OpenAPI document: 0.10.9
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateLnurlData {
    #[serde(rename = "description_hash")]
    pub description_hash: String,
    #[serde(rename = "callback")]
    pub callback: String,
    #[serde(rename = "amount")]
    pub amount: i32,
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl CreateLnurlData {
    pub fn new(description_hash: String, callback: String, amount: i32) -> CreateLnurlData {
        CreateLnurlData {
            description_hash,
            callback,
            amount,
            comment: None,
            description: None,
        }
    }
}


