/*
 * lnbits
 *
 * API for LNbits, the free and open source bitcoin wallet and accounts system with plugins.
 *
 * The version of the OpenAPI document: 0.10.9
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateExtension {
    #[serde(rename = "ext_id")]
    pub ext_id: String,
    #[serde(rename = "archive")]
    pub archive: String,
    #[serde(rename = "source_repo")]
    pub source_repo: String,
}

impl CreateExtension {
    pub fn new(ext_id: String, archive: String, source_repo: String) -> CreateExtension {
        CreateExtension {
            ext_id,
            archive,
            source_repo,
        }
    }
}


