/*
 * lnbits
 *
 * API for LNbits, the free and open source bitcoin wallet and accounts system with plugins.
 *
 * The version of the OpenAPI document: 0.10.9
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DecodePayment {
    #[serde(rename = "data")]
    pub data: String,
}

impl DecodePayment {
    pub fn new(data: String) -> DecodePayment {
        DecodePayment {
            data,
        }
    }
}


